### ISSUE TITLE
The very point of this addon which is AUTO discarding is broken

### ISSUE THREAD

**Issue by Deiwulf** [rNeomy/auto-tab-discard#314] opened 2022-10-07 13:43 UTC
Works manually though, yet even then sometimes requires shift override for tabs that don't have any forms or media playing.

FF Dev Edition 106.0b9 (64-bit) (and 5+ versions before - yes I have too much patience, or too lazy idk)

Edit: just tested with 0.5 version and that works right away.

**Comment by rNeomy** [comment] 2022-10-15 07:05
Duplicate of https://github.com/rNeomy/auto-tab-discard/issues/310

**Closed by rNeomy** 2022-10-15 07:05 UTC
