### ISSUE TITLE
Whilelist keeps reseting to default

### ISSUE THREAD

**Issue by Xalcer** [rNeomy/auto-tab-discard#208] opened 2021-02-21 14:54 UTC
Hi.

I just installed the extension on Chrome and works as expected, except the whitelist doesn't last long. After a few minutes, it goes blank again, ignoring whatever I've set.

**Comment by rNeomy** [comment] 2021-02-23 07:24
So if you add a new URL to the list and press the save button and close the options page, on the next open, you don't see the URL?

**Comment by Xalcer** [comment] 2021-02-23 11:45
If I open again inmediately it's still saved. It's after a few minutes or when I close and open the browser when it resets.

**Comment by rNeomy** [comment] 2021-02-28 08:15
do you have any policy for this extension? chrome://policy/

**Comment by Xalcer** [comment] 2021-02-28 11:19
No policies established.

**Comment by rNeomy** [comment] 2021-04-03 05:57
I am not sure what could cause this. Can you try the extension on a clean profile?

**Comment by inkhsutesou** [comment] 2021-04-15 15:59
![image](https://user-images.githubusercontent.com/4542497/114900644-124ae500-9de2-11eb-8a5b-5ad97ab51767.png)
Same issue

**Comment by rNeomy** [comment] 2021-04-15 17:25
The options page loads settings once it gets opened. So if you have it opened while you add a new hostname from the popup interface, you will need to refresh the page to see updates. Also, there is no need to save anything if you add hostnames from the popup interface.

**Comment by Soraph** [comment] 2021-04-22 12:08
I have the same issue even after the latest update, it discard everything and disregard the settings like pinned tabs and whitelist, if I reboot the browser I have the whitelist empty

**Comment by rNeomy** [comment] 2021-04-22 13:14
Let's debug:

1. Open "chrome://extensions/" in a browser tab and turn the developer mode on
2. Find the background page of this extension and switch to the Console tab
3. Type "chrome.runtime.reload()" and see if you get an error on the background page.

**Comment by Soraph** [comment] 2021-04-22 13:18
No errors

**Comment by rNeomy** [comment] 2021-04-24 06:24
@Soraph can you reproduce this on the latest release? v0.4.6

**Comment by Soraph** [comment] 2021-04-24 08:35
@rNeomy I can confirm that the issue is resolved with 0.4.6, I just checked with a browser restart and an OS restart (Brave on Win10). The options are persisted correctly and the tabs seems to behave as expected

**Comment by rNeomy** [comment] 2021-04-24 11:26
perfect! @Xalcer can you confirm too?

**Comment by Xalcer** [comment] 2021-04-24 15:23
It seems to work correctly now.

**Comment by endymion0000** [comment] 2021-04-27 22:18
There's still problems with the Exceptions whitelist in 0.4.6.

It still occasionally wipes the list and just now I had 2 domains in it from a previous session. I went to add about 4 or 5 new ones by visiting the sites one after the other and selecting Keep Tabs For This Site: Always. Reloaded the plugin options and the only one listed was the last one I did. The 2 were gone along with all of  the new ones except that last one.

So while the list can persist, it may be the adding to the list process that sometimes is going awry.

**Closed** 2021-04-28 04:06 UTC

**Comment by rNeomy** [comment] 2021-04-28 05:08
@endymion0000 Should have been fixed by the new release. Thanks for the report.

**Comment by endymion0000** [comment] 2021-04-28 05:15
I'll await the release of 0.4.7 and see.
