### ISSUE TITLE
"Discard newly opened tabs" feature buggy

### ISSUE THREAD

**Issue by tirphana** [rNeomy/auto-tab-discard#241] opened 2021-06-01 12:27 UTC
As per title, I’m having problems with this feature. Especially if I try opening multiple tabs with "Load Background Tabs Lazily" addon (which I find reasonable these 2 addons should support each other), only the first 2, 3 or 4 tabs (not sure what it depends on) are discarded and the rest load fully. One strange thing I noticed is that the first couple of discarded tabs for some reason have additional "zzz" favicons appended (the number of which again appears to be random). 

Running the option alone, with no addons also seemed to be buggy when opening more than ~75 tabs, in that it would sometimes swallow some tabs (as far as I tested, the more tabs I opened, the more of them misteriously disappeared).

I would appreciate if this issue is looked into, since it’s really important for loading a lot of tabs (loading a bookmark folder, for example).

**Comment by tirphana** [comment] 2021-07-28 11:28
Also, the "Discard newly opened tabs" option cannot be turned off without restarting the browser session.

**Comment by rNeomy** [comment] 2021-12-12 08:55
Thanks for the report. It should be fixed by the next release.

> Also, the "Discard newly opened tabs" option cannot be turned off without restarting the browser session.

I am not able to reproduce this though.

**Closed** 2021-12-12 08:54 UTC

**Comment by tirphana** [comment] 2022-01-02 01:48
> I am not able to reproduce this though.

Forgot to  update here, but I figured out some days after posting that just restarting the addon turns it off, haven't really tested it since. Also, big thanks for looking into the issues I posted. :)
