### ISSUE TITLE
Bug: "close tab" with single-tab window malfunctions

### ISSUE THREAD

**Issue by Luckz** [rNeomy/auto-tab-discard#264] opened 2021-12-22 18:48 UTC
On Chrome at least (didn't test on FF), it's always™ been the case that the close tab function (as assigned to a hotkey f.ex.) can break horrendously if you have a single-tab window in front. It can instead close the active tab of another window, I suppose when switching to another window with more tabs while ATD is still looking for that first tab to close (?), and this is really hard to spot for the user – either they quickly ctrl-shift-T after it happens, or they lose a tab forever without even knowing about it.

The peculiar thing is that this can happen several _minutes_ after pressing the hotkey.

**Comment by rNeomy** [comment] 2021-12-26 07:02
I am not able to reproduce this with the default settings. Can you confirm on a clean profile? I suspect this is a conflict with another extension of yours or a plug-in is responsible for closing a not-focused tab.

**Comment by rNeomy** [comment] 2021-12-26 07:31
I think I found the issue. Please reopen if you are still experiencing it after the 0.4.9 release.

**Closed by rNeomy** 2021-12-26 07:31 UTC

**Comment by Luckz** [comment] 2021-12-27 08:00
Now that you fixed that infinite loop problem, it seems safe to use. 👍🏻

Is it by the way WAD that the `Close Tab` hotkey (see above) won't close the last tab in a window?

**Comment by rNeomy** [comment] 2021-12-29 07:27
> Is it by the way WAD that the Close Tab hotkey (see above) won't close the last tab in a window?

No! Just a bug that is now fixed! Thanks for the report.
