### ISSUE TITLE
[Feature Request] Option to manually release a tab

### ISSUE THREAD

**Issue by ImAjayS** [rNeomy/auto-tab-discard#192] opened 2021-01-16 04:51 UTC
Instead of automatically unsuspending a tab, have an option to manually unsuspend it, and have the tab suspended when I click and open a suspended tab.

**Comment by diptopandit** [comment] 2021-01-19 20:17
Duplicate of #169

**Comment by rNeomy** [comment] 2021-04-03 06:16
closing in favor of #169

**Closed by rNeomy** 2021-04-03 06:16 UTC
