### ISSUE TITLE
[Bug] Auto unload not working properly

### ISSUE THREAD

**Issue by ReporterX** [rNeomy/auto-tab-discard#84] opened 2019-04-10 04:17 UTC
Firefox 66.0.2 (64-bit)  
Auto Tab Discard 0.3.1  
(All other addons are disabled and restart Firefox before testing)  
`browser.tabs.remote.autostart` is set to true.  

Settings:
10 seconds when inactive tabs exceeds 1  
-  [x] Display discarding items in the "tab" context menu  
-  [x] Display discarding items in the "page" context menu  
-  [x] Display "Open Link in New Discarded Tab"...  
-  [x] Change favicon of discarded tabs  
----
-  [x] Do not discard a tab when media is playing  
-  [x] Do not discard a tab when form changes are not yet submitted  
----
Toolbar left_click action  
-  [x] Open popup
----
-  [x] Discard a tab when it is hidden  

The rest are unselected.

I have around 40 tabs, all being inactive.

Then 4 tabs were loaded at different pages at addons.mozilla.org  
1 tab, at a page at github.com  
1 tab, at gitlab.com  
1 tab, at lifewire.com  

None were discarded after the time limit.

I tested several times before. A few tabs managed to be discarded automatically. I didn't record the steps so I'm not sure why a few could be auto-discarded successfully.

P.S. I disabled your addon and tested another auto-discard addon. That one works properly.

**Comment by rNeomy** [comment] 2019-05-26 13:04
> Then 4 tabs were loaded at different pages at addons.mozilla.org

No addon can discard pages from "addons.mozilla.org". They are protected for user safety.

For the rest, you can enable logging from the options page and then check the console log (Ctrl + Shift + J). If a tab meets the conditions, it should get discarded, otherwise the extension prints to the console window the reason why discarding is skipped.

**Comment by fra-san** [comment] 2019-11-27 09:45
I'm experiencing a similar issue to that of @ReporterX.

**Summary**: no tab is automatically discarded if at least one tab is browsing some specific URLs (e.g. addons.mozilla.org, support.mozilla.org).

**auto-tab-discard version**: 0.3.3
**Browser**: Firefox 70.0.1 (64-bit)
**Operating system**: Arch Linux

**auto-tab-discard preferences** (exported as JSON):

```json
{
  "chrome.storage.local": {
    "audio": true,
    "battery": false,
    "check-delay": 30000,
    "click": "click.popup",
    "faqs": true,
    "favicon": true,
    "favicon-delay": 500,
    "form": true,
    "go-hidden": false,
    "last-update": 1574842086768,
    "link.context": true,
    "log": false,
    "memory-enabled": false,
    "memory-value": 60,
    "mode": "time-based",
    "notification.permission": false,
    "number": 1,
    "online": false,
    "page.context": false,
    "period": 10,
    "pinned": false,
    "simultaneous-jobs": 10,
    "tab.context": true,
    "use-cache": false,
    "whitelist": [],
    "whitelist-url": []
  },
  "localStorage": {
    "click": "popup",
    "explore-count": "96"
  }
}
```

**Steps to reproduce**:

  - Create a fresh Firefox profile;
  - Install auto-tab-discard as the only add-on;
  - Open some tabs; four in my test, browsing:
    - https://www.google.com/
    - https://duckduckgo.com/
    - https://twitter.com/
    - https://support.mozilla.org/en-US/ (the only relevant one).

**Expected behavior**: The background tabs (i.e. all, except for the selected one) are discarded.

**Actual behavior**: No tab is discarded.

**Additional information**:

I get the expected behavior after closing the "https://support.mozilla.org/en-US/" tab. I.e. some mozilla.org subdomains seem to prevent _any_ other tab from being discarded.  
Please note that my point is not about discarding the support.mozilla.org—which is apparently not possible, as previously pointed out.

I'm consistently observing this behavior, regardless of the number of open tabs, the discarding options and the discarding conditions.

If "Display log" is enabled in auto-tab-discard preferences and support.mozilla.org is open in one tab:

1. The console of the tabs that should be discarded only shows:
    ```
    set a new timer 10          top.js:33:47
    request tabs.check          top.js:33:47
    ```
    (Nothing is logged about why they are not discarded).

2. Firefox debugger's console for the extension shows:
    ```
    tab.timeout                                                                                                                                 3 background.js:47:47
    tabs._check is called                                                                                                                         background.js:47:47
    arr > (4) […]                                                                                                                                 background.js:47:47
      0: Object { ready: true, now: 1574845804126, allowed: true, … }
      1: Object { ready: true, now: 1574845805166, allowed: true, … }
      2: Object { ready: true, now: 1574845805166, allowed: true, … }
      3: undefined
      length: 4
      <prototype>: Array []
    discardable > Object { exception: undefined, ready: true, now: 1574845804126, allowed: true, tabId: 3, tab: {…} } true true true true true    background.js:47:47
    discardable > Object { exception: undefined, ready: true, now: 1574845805166, allowed: true, tabId: 4, tab: {…} } true true true true true    background.js:47:47
    discardable > Object { exception: undefined, ready: true, now: 1574845805166, allowed: true, tabId: 6, tab: {…} } true true true true true    background.js:47:47
    TypeError: a is undefined                                                                                                                     background.js:222:9
    ```
    Note that no message about the number of discarded tabs is printed.
    
    Not surprisingly, when no problematic tab is open and tabs are correctly discarded the debugger's console shows no "undefined" elements in the `arr` array and no `TypeError` error. Also, the line `number of tabs being discarded 2` is printed.

**Comment by rNeomy** [comment] 2019-12-01 08:51
@ReporterX I am not able to reproduce this on the latest release. Please let me know if you still have the issue
@fra-san thanks for the report. It will get fixed by the next release.

**Closed by rNeomy** 2019-12-01 08:51 UTC
