### ISSUE TITLE
Clicking on some discarded tabs will not reload the page, but takes me to the blank home page

### ISSUE THREAD

**Issue by smorked** [rNeomy/auto-tab-discard#171] opened 2020-08-24 17:21 UTC
Clicking on some discarded tabs will not reload the page, but takes me to the blank home page

It's as if the cache cannot be found and the page has been deleted/trashed. 
This is random and can happen moments after the page was discarded or hours later.

Windows 10
Firefox: 79.0
auto-tab-discard version: 0.3.7

**Comment by Kobberholm** [comment] 2020-10-08 17:06
I can confirm this issue also happens to me. 
A major issue, is that the address bar is also empty, so there is no easy way of getting back to the page.
Kubuntu 19.10
Firefox 78.0.2 (64-bit)

**Enabled addons:**
Absolute Enable Right Click & Copy 1.3.8
Amazon Container 2.0.0
Amazon.com 1.1
Auto Tab Discard 0.3.7
Awesome RSS 1.3.5
BetterTTV 7.2.89
Bing 1.1
Bitwarden - Free Password Manager 1.46.2
Bookmark Tree for Tree Style Tab 4.1
Container Tabs Sidebar 0.3.5
Containers theme 1.0.3
Copy Selected Links 2.1.5
Decentraleyes 2.0.14
Don't touch my tabs! (rel=noopener) 2.2.0
DownThemAll! 4.2.6
DuckDuckGo 1
Easy Screenshot 3.67
eBay 1
Enhancer for YouTube™ 2.0.101
Export Tabs URLs 0.2.12
Facebook Container 2.1.2
Firefox Multi-Account Containers 7.1.0
Google 1
Google Container 1.5.1
Greasemonkey 4.10.0
HTTPS Everywhere 2020.8.13
I don't care about cookies 3.2.2
LinkedIn Container 1.2.5
Open bookmark in Container Tab menu item 1.3
Plasma Integration 1.7.6
QOwnNotes Web Companion 20.10.0
Reddit Container 1.0.2
ReloadMatic 1.7.0
Request Control 1.15.5
RESTED 2.3.1
Save Page WE 23
Session Sync 3.1.12
Skip Redirect 2.3.4
Temporary Containers 1.9.1
Terms of Service; Didn’t Read 2.0.0
Tree Style Tab 3.5.31
TST Colored Tabs 0.7
Twitter Container 1.3.1
uBlock Origin 1.30.0
Video DownloadHelper 7.3.9
Vue.js devtools 5.3.3
Web Archives 2.1.0
Wikipedia (en) 1
YouTube Auto Like 3.2.3

**Comment by kernc** [comment] 2020-11-07 16:16
Duplicate of https://github.com/rNeomy/auto-tab-discard/issues/95.

**Comment by rNeomy** [comment] 2021-01-26 12:58
This should be fixed by the next release.

**Closed by rNeomy** 2021-01-26 12:58 UTC
